// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: dummy/v1/service.proto

package dummyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetDummyRequest) Reset() {
	*x = GetDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummy_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyRequest) ProtoMessage() {}

func (x *GetDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummy_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyRequest.ProtoReflect.Descriptor instead.
func (*GetDummyRequest) Descriptor() ([]byte, []int) {
	return file_dummy_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDummyRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetDummyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetDummyResponse) Reset() {
	*x = GetDummyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummy_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyResponse) ProtoMessage() {}

func (x *GetDummyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dummy_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyResponse.ProtoReflect.Descriptor instead.
func (*GetDummyResponse) Descriptor() ([]byte, []int) {
	return file_dummy_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDummyResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_dummy_v1_service_proto protoreflect.FileDescriptor

var file_dummy_v1_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x5f, 0x0a, 0x0c, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x6f, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x75, 0x6d,
	0x6d, 0x79, 0x3b, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dummy_v1_service_proto_rawDescOnce sync.Once
	file_dummy_v1_service_proto_rawDescData = file_dummy_v1_service_proto_rawDesc
)

func file_dummy_v1_service_proto_rawDescGZIP() []byte {
	file_dummy_v1_service_proto_rawDescOnce.Do(func() {
		file_dummy_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_dummy_v1_service_proto_rawDescData)
	})
	return file_dummy_v1_service_proto_rawDescData
}

var file_dummy_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dummy_v1_service_proto_goTypes = []interface{}{
	(*GetDummyRequest)(nil),  // 0: proto.dummy.v1.GetDummyRequest
	(*GetDummyResponse)(nil), // 1: proto.dummy.v1.GetDummyResponse
}
var file_dummy_v1_service_proto_depIdxs = []int32{
	0, // 0: proto.dummy.v1.DummyService.GetDummy:input_type -> proto.dummy.v1.GetDummyRequest
	1, // 1: proto.dummy.v1.DummyService.GetDummy:output_type -> proto.dummy.v1.GetDummyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dummy_v1_service_proto_init() }
func file_dummy_v1_service_proto_init() {
	if File_dummy_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dummy_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummy_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dummy_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummy_v1_service_proto_goTypes,
		DependencyIndexes: file_dummy_v1_service_proto_depIdxs,
		MessageInfos:      file_dummy_v1_service_proto_msgTypes,
	}.Build()
	File_dummy_v1_service_proto = out.File
	file_dummy_v1_service_proto_rawDesc = nil
	file_dummy_v1_service_proto_goTypes = nil
	file_dummy_v1_service_proto_depIdxs = nil
}
